### ISSUE TITLE
Running HexGen without FlashAttention

### ISSUE THREAD

**Issue by Esthesia** [Relaxed-System-Lab/HexGen#2]
I want to know how to run the HexGen without FlashAttention since FlashAttention is supported Ampere Generation.
I can revise the model code whole for not using FlashAttention, but I'm just curious about disabling in easy way.

Thank you.

**Comment by Youhe-Jiang** [comment]
Given that the model we employ operates using flash attention, it is possible to deactivate flash attention by defaulting the 'config.use_flash_attn' parameter to 'False' within the definition of the 'config' option in the GPTLMHeadModel, which represents the implemented model. Alternatively, in the upcoming version of hexgen, we will incorporate a feature enabling the straightforward disabling of flash attention by providing corresponding arguments. Thank you for your inquiry.

**Comment by Esthesia** [comment]
@Youhe-Jiang Thanks for the quick response. I'll keep tracking on this repo.
